### ISSUE TITLE
914 doesn't use custom recipes

### ISSUE THREAD

**Issue by MrMadMask** [Badhamknibbs/SCPCB_DunGen_LC#25] opened 2024-02-09 17:15 UTC
Hello,
after following the written instructions in the README to add custom recipes, the 914 machine refuses to use the .json where I write the new recipes. I've tried carefully spellchecking the whole code, removing the default.json, renaming the custom one to "default", but the 914 either always picks the default.json or completely ignores the other one. I'm at my wits' end trying to get it to work, so I hope at least someone here can help me understand what I'm doing wrong. I'll leave the code I'm trying to use for custom recipes below. Thank you for any help.

```
[
{"ItemName":"airhorn", "RoughResults":["*"], "CoarseResults":["clown horn"], "OneToOneResults":["@", "clown horn"], "FineResults":["@", "bell"], "VeryFineResults":["bell"]},
{"ItemName":"army canteen", "RoughResults":["*", "plastic fish"], "CoarseResults":["plastic fish"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["@", "army helmet"]},
{"ItemName":"army helmet", "RoughResults":["metal sheet"], "CoarseResults":["army canteen"], "OneToOneResults":["@"], "FineResults":["@", "tea kettle"], "VeryFineResults":["toy tank"]},
{"ItemName":"bell", "RoughResults":["clown horn"], "CoarseResults":["airhorn"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["@", "*", "weezer guitar"]},
{"ItemName":"big bolt", "RoughResults":["*"], "CoarseResults":["metal sheet"], "OneToOneResults":["@"], "FineResults":["large axle"], "VeryFineResults":["v-type engine", "lockpicker"]},
{"ItemName":"blue test tube", "RoughResults":["*"], "CoarseResults":["test tube"], "OneToOneResults":["green test tube", "red test tube", "yellow test tube"], "FineResults":["test tube rack"], "VeryFineResults":["*"]},
{"ItemName":"bottles", "RoughResults":["*"], "CoarseResults":["metal sheet"], "OneToOneResults":["@", "test tube"], "FineResults":["blue test tube", "green test tube", "red test tube", "yellow test tube"], "VeryFineResults":["*"]},
{"ItemName":"brain jar", "RoughResults":["*"], "CoarseResults":["*", "nutcracker eye"], "OneToOneResults":["jar of pickles"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"brush", "RoughResults":["*"], "CoarseResults":["pill bottle"], "OneToOneResults":["@", "dust pan"], "FineResults":["*", "hair dryer"], "VeryFineResults":["hair dryer"]},
{"ItemName":"bunny ears", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["*"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"candy", "RoughResults":["comedy"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["toothpaste"], "VeryFineResults":["toothpaste"]},
{"ItemName":"cash register", "RoughResults":["gold bar", "gift"], "CoarseResults":["*", "gold bar"], "OneToOneResults":["@", "typewriter"], "FineResults":["@"], "VeryFineResults":["*", "jar of pickles"]},
{"ItemName":"chemical jug", "RoughResults":["red soda"], "CoarseResults":["perfume bottle", "pill bottle"], "OneToOneResults":["@"], "FineResults":["jar of pickles"], "VeryFineResults":["jar of pickles"]},
{"ItemName":"clown horn", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["airhorn", "@"], "FineResults":["airhorn"], "VeryFineResults":["bell"]},
{"ItemName":"comedy", "RoughResults":["tragedy"], "CoarseResults":["tragedy"], "OneToOneResults":["tragedy"], "FineResults":["tragedy"], "VeryFineResults":["tragedy"]},
{"ItemName":"cookie mold pan", "RoughResults":["comedy"], "CoarseResults":["@", "candy", "egg beater"], "OneToOneResults":["@", "test tube rack"], "FineResults":["tea kettle"], "VeryFineResults":["@"]},
{"ItemName":"corner pipe", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["flow pipe"], "FineResults":["flow pipe"], "VeryFineResults":["large axle"]},
{"ItemName":"dust pan", "RoughResults":["*"], "CoarseResults":["@"], "OneToOneResults":["@", "brush", "egg beater"], "FineResults":["@"], "VeryFineResults":["skillet"]},
{"ItemName":"egg beater", "RoughResults":["*"], "CoarseResults":["@"], "OneToOneResults":["@", "brush", "egg beater"], "FineResults":["skillet"], "VeryFineResults":["potatoes"]},
{"ItemName":"fancy lamp", "RoughResults":["*", "flashlight", "stun grenade"], "CoarseResults":["@", "pro-flashlight", "stun grenade"], "OneToOneResults":["@", "laser pointer"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"fire axe", "RoughResults":["*", "shovel"], "CoarseResults":["@", "shovel", "stop sign"], "OneToOneResults":["@", "yield sign", "stop sign"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"flask", "RoughResults":["*"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["golden cup", "jar of pickles"]},
{"ItemName":"flow pipe", "RoughResults":["small pipe"], "CoarseResults":["corner pipe"], "OneToOneResults":["corner pipe"], "FineResults":["large axle"], "VeryFineResults":["large axle"]},
{"ItemName":"gift", "RoughResults":["*"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["golden cup"]},
{"ItemName":"gold bar", "RoughResults":["*"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["golden cup"]},
{"ItemName":"golden cup", "RoughResults":["dust pan", "flask"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["magnifying glass"]},
{"ItemName":"gramophone", "RoughResults":["dust pan", "flask"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["magnifying glass"]},
{"ItemName":"green test tube", "RoughResults":["*"], "CoarseResults":["test tube"], "OneToOneResults":["blue test tube", "red test tube", "yellow test tube"], "FineResults":["test tube rack"], "VeryFineResults":["*"]},
{"ItemName":"hairdryer", "RoughResults":["dust pan", "flask"], "CoarseResults":["mug", "pill bottle", "red soda"], "OneToOneResults":["@"], "FineResults":["magnifying glass"], "VeryFineResults":["magnifying glass"]},
{"ItemName":"homemade flashbang", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["stun grenade"], "VeryFineResults":["stun grenade", "*", "zap gun"]},
{"ItemName":"jar of pickles", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@", "@", "@", "brain jar"], "FineResults":["*", "golden cup"], "VeryFineResults":["*", "*", "*", "*", "bunnny ears"]},
{"ItemName":"key", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["lockpicker", "metal sheet"], "VeryFineResults":["lockpicker"]},
{"ItemName":"large axle", "RoughResults":["metal sheet"], "CoarseResults":["big bolt"], "OneToOneResults":["@"], "FineResults":["v-type engine", "lockpicker"], "VeryFineResults":["lockpicker", "lockpicker", "toy robot", "*"]},
{"ItemName":"laser pointer", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@", "flashlight"], "FineResults":["homemade flashbang", "@"], "VeryFineResults":["stun grenade", "homemade flashbang"]},
{"ItemName":"magic 7 ball", "RoughResults":["@"], "CoarseResults":["@"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"magnifying glass", "RoughResults":["flask"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["flashlight", "@"], "VeryFineResults":["*", "homemade flashbang", "flashlight"]},
{"ItemName":"metal sheet", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["big bolt"], "VeryFineResults":["large axle", "lockpicker"]},
{"ItemName":"mug", "RoughResults":["syringe"], "CoarseResults":["big bolt"], "OneToOneResults":["test tube"], "FineResults":["*"], "VeryFineResults":["blue test tube", "green test tube", "red test tube", "yellow test tube"]},
{"ItemName":"nutcracker eye", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["*"], "VeryFineResults":["shotgun"]},
{"ItemName":"old phone", "RoughResults":["*", "metal sheet"], "CoarseResults":["@"], "OneToOneResults":["walkie-talkie", "@"], "FineResults":["@", "old radio"], "VeryFineResults":["boombox"]},
{"ItemName":"old radio", "RoughResults":["*", "metal sheet"], "CoarseResults":["gramophone"], "OneToOneResults":["radar booster", "@"], "FineResults":["@", "old phone"], "VeryFineResults":["boombox"]},
{"ItemName":"painting", "RoughResults":["spray paint"], "CoarseResults":["@"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["*"]},
{"ItemName":"perfume bottle", "RoughResults":["*"], "CoarseResults":["pill bottle"], "OneToOneResults":["@"], "FineResults":["chemical jug"], "VeryFineResults":["hair dryer", "test tube"]},
{"ItemName":"pill bottle", "RoughResults":["*"], "CoarseResults":["flask"], "OneToOneResults":["@"], "FineResults":["perfume bottle", "chemical jug"], "VeryFineResults":["chemical jug"]},
{"ItemName":"plastic fish", "RoughResults":["*"], "CoarseResults":["*", "pill bottle"], "OneToOneResults":["@"], "FineResults":["perfume bottle", "chemical jug"], "VeryFineResults":["chemical jug"]},
{"ItemName":"potatoes", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["*", "jar of pickles"]},
{"ItemName":"red soda", "RoughResults":["*"], "CoarseResults":["*", "pill bottle"], "OneToOneResults":["@", "red test tube"], "FineResults":["jar of pickles"], "VeryFineResults":["chemical jug", "golden cup"]},
{"ItemName":"red test tube", "RoughResults":["red soda"], "CoarseResults":["test tube"], "OneToOneResults":["green test tube", "blue test tube", "yellow test tube"], "FineResults":["test tube rack"], "VeryFineResults":["*"]},
{"ItemName":"remote", "RoughResults":["*"], "CoarseResults":["*", "old radio"], "OneToOneResults":["@", "old phone"], "FineResults":["@"], "VeryFineResults":["radar booster"]},
{"ItemName":"ring", "RoughResults":["gold bar"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["*"]},
{"ItemName":"rockinghorse", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["*"]},
{"ItemName":"rubber ducky", "RoughResults":["*"], "CoarseResults":["toy car"], "OneToOneResults":["toy cube"], "FineResults":["toy nutcracker", "toy robot"], "VeryFineResults":["warplane toy", "toy tank"]},
{"ItemName":"skillet", "RoughResults":["dust pan"], "CoarseResults":["*"], "OneToOneResults":["@", "egg beater"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"small pipe", "RoughResults":["*"], "CoarseResults":["big bolt"], "OneToOneResults":["@"], "FineResults":["corner pipe"], "VeryFineResults":["flow pipe"]},
{"ItemName":"steering wheel", "RoughResults":["wirespool"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["large axle"]},
{"ItemName":"stop sign", "RoughResults":["*"], "CoarseResults":["shovel"], "OneToOneResults":["@", "yield sign"], "FineResults":["*"], "VeryFineResults":["*", "*", "fire axe"]},
{"ItemName":"syringe", "RoughResults":["*"], "CoarseResults":["*", "@"], "OneToOneResults":["@", "test tube", "pill bottle"], "FineResults":["syringe gun", "@"], "VeryFineResults":["chemical jug"]},
{"ItemName":"syringe gun", "RoughResults":["flask"], "CoarseResults":["syringe", "pill bottle"], "OneToOneResults":["@"], "FineResults":["jar of pickles"], "VeryFineResults":["brain jar"]},
{"ItemName":"tape player log 1", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["tape player log 4", "tape player log 2", "tape player log 3"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"tape player log 2", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["tape player log 1", "tape player log 4", "tape player log 3"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"tape player log 3", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["tape player log 1", "tape player log 2", "tape player log 4"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"tape player log 4", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["tape player log 1", "tape player log 2", "tape player log 3"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"tea kettle", "RoughResults":["*"], "CoarseResults":["flask"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["chemical jug", "golden cup"], "brain jar"},
{"ItemName":"teeth", "RoughResults":["candy"], "CoarseResults":["toothpaste"], "OneToOneResults":["@"], "FineResults":["teeth"], "VeryFineResults":["teeth"]},
{"ItemName":"test tube", "RoughResults":["*"], "CoarseResults":["syringe"], "OneToOneResults":["@"], "FineResults":["blue test tube", "green test tube", "red test tube", "yellow test tube"], "VeryFineResults":["test tube rack"]},
{"ItemName":"test tube rack", "RoughResults":["syringe"], "CoarseResults":["blue test tube", "green test tube", "red test tube", "yellow test tube", "test tube"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"toothpaste", "RoughResults":["*"], "CoarseResults":["candy"], "OneToOneResults":["@"], "FineResults":["teeth"], "VeryFineResults":["teeth"]},
{"ItemName":"toy car", "RoughResults":["rubber ducky"], "CoarseResults":["toy cube", "toy robot"], "OneToOneResults":["@", "toy nutcracker"], "FineResults":["toy tank"], "VeryFineResults":["warplane toy"]},
{"ItemName":"toy cube", "RoughResults":["rubber ducky"], "CoarseResults":["toy car"], "OneToOneResults":["@", "toy nutcracker"], "FineResults":["toy tank", "warplane toy"], "VeryFineResults":["toy tank", "warplane toy"]},
{"ItemName":"toy nutcracker", "RoughResults":["rubber ducky"], "CoarseResults":["toy cube", "toy car"], "OneToOneResults":["@", "nutcracker eye", "toy robot"], "FineResults":["tank toy", "warplane toy"], "VeryFineResults":["shotgun"]},
{"ItemName":"toy robot", "RoughResults":["metal sheet"], "CoarseResults":["v-type engine"], "OneToOneResults":["@", "toy nutcracker"], "FineResults":["toy car", "toy tank"], "VeryFineResults":["toy tank"]},
{"ItemName":"toy tank", "RoughResults":["metal sheet"], "CoarseResults":["v-type engine"], "OneToOneResults":["@", "warplane toy"], "FineResults":["@"], "VeryFineResults":["shotgun"]},
{"ItemName":"tragedy", "RoughResults":["comedy"], "CoarseResults":["comedy"], "OneToOneResults":["comedy"], "FineResults":["comedy"], "VeryFineResults":["comedy"]},
{"ItemName":"typewriter", "RoughResults":["old phone"], "CoarseResults":["@"], "OneToOneResults":["cash register", "@"], "FineResults":["@"], "VeryFineResults":["@", "comedy", "tragedy"]},
{"ItemName":"v-type engine", "RoughResults":["metal sheet"], "CoarseResults":["big bolt", "large axle"], "OneToOneResults":["@"], "FineResults":["lockpicker", "toy robot"], "VeryFineResults":["toy robot", "toy robot", "*", "jetpack"]},
{"ItemName":"warplane toy", "RoughResults":["metal sheet"], "CoarseResults":["toy tank"], "OneToOneResults":["toy robot", "@"], "FineResults":["*", "@"], "VeryFineResults":["@", "*", "*", "jetpack"]},
{"ItemName":"weezer guitar", "RoughResults":["clown horn", "airhorn"], "CoarseResults":["airhorn", "bell"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["boombox"]},
{"ItemName":"wheelrim", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["stop sign", "yield sign"], "VeryFineResults":["*"]},
{"ItemName":"whoopie cushion", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["bell"]},
{"ItemName":"wirespool", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"yellow test tube", "RoughResults":["*"], "CoarseResults":["test tube"], "OneToOneResults":["green test tube", "red test tube", "blue test tube"], "FineResults":["test tube rack"], "VeryFineResults":["*"]},
{"ItemName":"yield sign", "RoughResults":["*"], "CoarseResults":["shovel"], "OneToOneResults":["@", "yield sign"], "FineResults":["stop sign"], "VeryFineResults":["*", "*", "fire axe"]},
{"ItemName":"boombox", "RoughResults":["whoopie cushion"], "CoarseResults":["*", "bell"], "OneToOneResults":["@", "old radio"], "FineResults":["*"], "VeryFineResults":["weezer guitar"]},
{"ItemName":"extension ladder", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"jetpack", "RoughResults":["v-type engine"], "CoarseResults":["warplane toy"], "OneToOneResults":["@", "*"], "FineResults":["*"], "VeryFineResults":["*"]},
{"ItemName":"lockpicker", "RoughResults":["metal sheet"], "CoarseResults":["*", "key"], "OneToOneResults":["@", "key"], "FineResults":["@"], "VeryFineResults":["@"]},
{"ItemName":"radar booster", "RoughResults":["*"], "CoarseResults":["walkie-talkie"], "OneToOneResults":["@", "walkie-talkie"], "FineResults":["@"], "VeryFineResults":["gramophone"]},
{"ItemName":"spray paint", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["*", "painting"]},
{"ItemName":"stun grenade", "RoughResults":["homemade flashbang", "*"], "CoarseResults":["flashlight", "*"], "OneToOneResults":["pro-flashlight", "*"], "FineResults":["@", "*"], "VeryFineResults":["*", "*", "*", "*", "zap gun"]},
{"ItemName":"tzp-inhalant", "RoughResults":["candy"], "CoarseResults":["@"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["candy"]},
{"ItemName":"zap gun", "RoughResults":["homemade flashbang"], "CoarseResults":["stun grenade"], "OneToOneResults":["@", "stop sign"], "FineResults":["*"], "VeryFineResults":["*",]},
{"ItemName":"flashlight", "RoughResults":["*"], "CoarseResults":["laser pointer", "@"], "OneToOneResults":["@"], "FineResults":["pro-flashlight", "@"], "VeryFineResults":["*", "fancy lamp", "stun grenade"]},
{"ItemName":"pro-flashlight", "RoughResults":["laser pointer"], "CoarseResults":["flashlight", "@"], "OneToOneResults":["@"], "FineResults":["stun grenade", "fancy lamp", "*"], "VeryFineResults":["*", "fancy lamp"]},
{"ItemName":"shovel", "RoughResults":["*"], "CoarseResults":["*"], "OneToOneResults":["@"], "FineResults":["stop sign", "yield sign"], "VeryFineResults":["*"]},
{"ItemName":"walkie-talkie", "RoughResults":["*"], "CoarseResults":["@"], "OneToOneResults":["@", "old phone"], "FineResults":["@", "boombox"], "VeryFineResults":["boombox"]}
]
```

**Comment by Badhamknibbs** [comment] 2024-02-09 22:39
Can you show your file directory structure leading to your custom json, and possibly a log file? The file directory structure needs to be quite specific.

**Comment by Badhamknibbs** [comment] 2024-02-09 22:54
Just ran a quick test, you made a typo where the log tells you the problem:
`[Error  :SCPCBDunGen] Failed to deserialize file: E:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\SCPCBDunGen\badhamknibbs-scp914-recipes\custom.json. Exception: Invalid character after parsing property name. Expected ':' but got: }. Path '[62].VeryFineResults', line 64, position 182.`

It's telling you the problem is on line 64, 182 characters in, where the issue is clear:
`{"ItemName":"tea kettle", "RoughResults":["*"], "CoarseResults":["flask"], "OneToOneResults":["@"], "FineResults":["@"], "VeryFineResults":["chemical jug", "golden cup"], "brain jar"},`

It looks like you were trying to add brain jar to the very fine results; moving it into the array like so:
`"VeryFineResults":["chemical jug", "golden cup", "brain jar"]},`
Loads the recipes.

**Closed as completed by Badhamknibbs** 2024-02-09 22:54 UTC

**Comment by MrMadMask** [comment] 2024-02-10 08:39
Oh, thank you very much. I'll pay more attention to the logs going forward.
